'use client';

import './globals.css';
import type { Metadata } from 'next';
import ThemeContextProvider from '@/context/ThemeContextProvider';
import App from '@/components/App/App';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <ThemeContextProvider>
      <App>{children}</App>
    </ThemeContextProvider>
  );
};

export default RootLayout;
