-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgIVZAmS4bOIngLLhS
mgfrz27p+BTN4/W3d0tNkEP+oAqgCgYIKoZIzj0DAQehRANCAASBVdxnhLHkJTzK
at7OXF4sBHWWrNvqTdtY+fbokkkGtEov+RSrDoh9J6XQGkTad7PpUYwsJJX/1AOy
rB5k7KQ2
-----END PRIVATE KEY-----